//geometry started in 200? by Luke Sutton
//script by chrissstrahl 20165.21.01 ulm, germany

void main();
void fightSequence1_secret();
void fightSequence1();
void fightSequence2();
void fightSequence2dot5();
void fightSequence3();
void endPosEnemyKilled();

float fEndPosEnemyKilled = 0;

//hzm coop mod - chrissstrahl - include the required coop level-scripts
/////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////
void	coop_endLevel();
entity	entityPlayerGlobal;

#include "coop_mod/matrix/main.scr"
#include "coop_mod/matrix/global/global_common.scr"
/////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////


void main()
{
	$triggerExit.missionobjective(1);

//register weapon in the script inventory (players respawn with this)
	globalCoop_armory_weaponRegister("models/weapons/worldmodel-Tricorder-stx.tik");
	globalCoop_armory_weaponRegister("models/weapons/worldmodel-Phaser-stx.tik");
	globalCoop_armory_weaponRegister("models/weapons/worldmodel-BurstRifle.tik");
	globalCoop_armory_weaponRegister("models/weapons/worldmodel-CompressionRifle.tik");

	//structural view mode
	$world.addAvailableViewMode("structuralintegrity");
	
	soundtrack( "music/dm_kw.mus" );
  
	//hzm coop mod chrissstrahl - author
	coop_string_levelAuthor = "Luke^0_^8Sutton";
	
	//hzm coop mod chrissstrahl - declare objectives - english
	coop_string_objectiveItem1 = "Help the Attrexians and defeat the Romulan invaders.";
	//coop_string_objectiveItem2 = "Find a Attrexian Archlauncher, you will need it.";
	coop_string_objectiveItem2 = "Restore Power to door, and enter the colony.";
	coop_string_objectiveItem3 = "Enter the building.";
	coop_string_objectiveItem4 = "Continue to the control room.";
	coop_string_objectiveTacticalInfo1 = "";//Use the distraction to your own advantage
	
	//hzm coop mod chrissstrahl - declare objectives - german
	coop_string_objectiveItem1_deu = "Helfen Sie den Attrexianern und besiegen Sie die romulanischen Eindringlinge.";
	//coop_string_objectiveItem2_deu = "Finden Sie einen Attrexianischen Bogenwerfer, den werden Sie brauchen.";
	coop_string_objectiveItem2_deu = "Stellen Sie die Energie der T$$u$$re wieder her, betreten Sie die Kolonie.";
	coop_string_objectiveItem3_deu = "Betreten Sie das Geb$$a$$ude.";
	coop_string_objectiveItem4_deu = "Gehen Sie weiter zum Kommandoraum.";
	coop_string_objectiveTacticalInfo1_deu = "";//N$$u$$tzen Sie die Verwirrung zu Ihrem Vorteil
	
	coop_string_story = "Date: Jan 2388. USS Odyssey-A has been ordered to fight off an orbiting warbird, and liberate the planet. You and your teammates must battle through the streets of Attrexia and protect the population from Romulan invasion.";
	coop_string_story_deu = "Datum: Jan 2388. Die USS Odyssey-A wurde entsannt um einen Warbird zu vertreiben und den Planeten zu befreien. Sie und Ihr Team m$$u$$ssen sich durch die Stra$$S$$en von Attrexia k$$a$$mpfen und die Bev$$o$$lkerung vor den romulanischen Invsoren sch$$u$$tzen.";
	
	//Remove archetype
	//$t43.archetype("");

	waitforplayer();
	
//update objectives - reroute power
	globalCoop_objectives_update("incomplete" , 1 , 0 );//help attrax
	globalCoop_objectives_update("complete" , 2 , 0 );//restore power to door
	globalCoop_objectives_update("complete" , 3 , 0 );//enter building
	globalCoop_objectives_update("incomplete" , 4 , 1 );//enter building
	
	//hzm coop mod chrissstrahl - Wait until the Game Starts in Multiplayer
	globalCoop_main_waitForWarmupTime();
	
	//hzm activate team ai
	$hazardTeam1.ai_on();
	
	//hzm remove archetype
	/* //disabled 
	$explosiveBarrel.archetype("");
	$hazardTeam1.archetype("");
	$healthConsole.archetype("");
	$ammoConsole.archetype("");
	*/
}

void fightSequence1_secret()
{
	//hzm register weapon, give upon spawn
	globalCoop_armory_weaponRegister("models/weapons/worldmodel-Tricorder-stx.tik");
	wait(5);
	
	//hzm give weapon now to all players
	globalCoop_player_giveAll("models/weapons/worldmodel-batleth.tik",1);
	
	//hzm remove bathleth
	if(doesEntityExist($secretBathleth)){
		$secretBathleth.remove();
	}
}

void fightSequence1()
{	
	//activate fighting party
	$fightSequence1_1.ai_on();
	$fightSequence1_2.ai_on();
	
	$fightSequence1_1.aggressive(1);
	$fightSequence1_2.aggressive(1);
}

void fightSequence2()
{	
	//activate fighting party
	$fightSequence2_1.ai_on();
	$fightSequence2_2.ai_on();
	$fightSequence2_3.ai_on();
	$fightSequence2_4.ai_on();
	$fightSequence2_5.ai_on();
	
	$fightSequence2_1.aggressive(1);
	$fightSequence2_2.aggressive(1);
	$fightSequence2_3.aggressive(1);
	$fightSequence2_4.aggressive(1);
	$fightSequence2_5.aggressive(1);
}

void fightSequence2dot5()
{	
	//activate fighting party
	$fightSequence2dot5_1.ai_on();
	$fightSequence2dot5_2.ai_on();
	
	$fightSequence2dot5_1.aggressive(1);
	$fightSequence2dot5_2.aggressive(1);
}

void fightSequence3()
{	
	//activate fighting party
	$fightSequence3_2.ai_on();
	$fightSequence3_3.ai_on();
	
	$fightSequence3_2.aggressive(1);
	$fightSequence3_3.aggressive(1);
}

void endPosEnemyKilled()
{
	fEndPosEnemyKilled++;
	if(fEndPosEnemyKilled == 3){
		$exitTrigger.triggerable();
		wait(3);
		thread coop_endLevel();
	}
}

void coop_endLevel()
//------------------------------------------------------------------------------
//Level end
//------------------------------------------------------------------------------
{
//mark this map as completed to the scripts (can not fail anymore)
	//globalCoop_mission_accomplished();
//credits, and history of map
	//globalCoop_main_globalCommand("nodamage");
	//globalCoop_huds_AddAll("coop_rotec_credits");
	//wait(10);
//load next map
	thread globalCoop_mission_completed("coop_rotec4");
}



