//-----------------------------------------------------------------------------------
// Script By:		Christian Sebastian Strahl (Chrissstrahl)
// Created on:		2010.02.15
// E-Mail:			chrissstrahl@yahoo.de
// Organisation:	HaZardModding

//HANDLES THINGS FOR SP AND MP

//
//CONTACT: chrissstrahl@yahoo.de [Christian Sebastian Strahl, Germany]
//-----------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------

////////////////////////////////////////////////////////////////////////////////
//DECLARATIONS
////////////////////////////////////////////////////////////////////////////////
void singleplayerCompatibilityHudprint(entity ePlayer,string sText)
{//hudprint does not work in SP, use centerprint instead
	if(cvar_bool_multiplayer){//MULTIPLAYER
		ePlayer.hudprint(sText);
	}else{
		centerPrint(sText);
	}
}


