void main();
void coop_endLevel();

//Co-op - noscript modul - trigger and prescripted based mission scripting extension
/////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////
#include "coop_mod/matrix/noscript.scr"
/////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////

void main()
{
//Co-Op
/////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////
//Start the Co-Op Script
	globalCoop_main();
//START SETUP ROUTINE\
	wait(1);
	thread coop_setuplevel();
}

void coop_endLevel()
//------------------------------------------------------------------------------
//Level end - End the current level, SUCESSFULLY
//And load the map specified on the mission complete trigger with->uservar1
//------------------------------------------------------------------------------
{
	//[b609] chrissstrahl - load prf_destructible instead of zoo1
	thread globalCoop_mission_completed("coop_test-destructible");
}


