resource 
Label
{
	cvarvisibility coop_ui_vt 16 ==
	
	title "$$c#040$$"
	name "coopAftermathModLevelsTitle"
	rect		274 89 330 24
	fgcolor 1.000 0.000 0.000 0.800
	bgcolor 0.12 0.15 0.25 1.00
	
	borderstyle "3D_BORDER"
	
	horizontaljustify left
	verticaljustify top
	font 	serpentinemedium-10
	
	hovercommand "globalwidgetcommand tooltip_coop_startserver title \"\""
    hoverexitcommand "globalwidgetcommand tooltip_coop_startserver title \"\""
}
resource
Button
{
	cvarvisibility coop_ui_vt 16 ==
	title "Episode 1 - The City Part 1"
	name 	"coopAftermathModLevels0"
	rect	275 114 328 20
	font serpentinemedium-10
	fgcolor 		1.000 1.000 1.000 0.800
	bgcolor 		0.12 0.15 0.25 0.7
	hoverbgcolor 	0.22 0.25 0.35 1.0
	
	horizontaljustify left
	verticaljustify top

	clicksound sound/misc/menu/click.wav
 
	stuffcommand "set ui_startmap coop_aftermath1\n"
	hovercommand "globalwidgetcommand coop_startserverShot shader sysimg/mapshots/coop_aftermath1.tga;globalwidgetcommand coop_startserverName title \"Daedalus\""
	hoverexitcommand "globalwidgetcommand coop_startserverShot shader sysimg/2d/default-map-screen.tga;globalwidgetcommand coop_startserverName title \"\""
}
resource
Button
{
	cvarvisibility coop_ui_vt 16 ==
	title "Episode 1 - The City Part 2"
	name 	"coopAftermathModLevels1"
	rect	275 135 328 20
	font serpentinemedium-10
	fgcolor 		1.000 1.000 1.000 0.800
	bgcolor 		0.12 0.15 0.25 0.7
	hoverbgcolor 	0.22 0.25 0.35 1.0
	
	horizontaljustify left
	verticaljustify top

	clicksound sound/misc/menu/click.wav
 
	stuffcommand "set ui_startmap coop_aftermath2\n"
	hovercommand "globalwidgetcommand coop_startserverShot shader sysimg/mapshots/coop_aftermath2.tga;globalwidgetcommand coop_startserverName title \"Daedalus\""
	hoverexitcommand "globalwidgetcommand coop_startserverShot shader sysimg/2d/default-map-screen.tga;globalwidgetcommand coop_startserverName title \"\""
}
resource
Button
{
	cvarvisibility coop_ui_vt 16 ==
	title "Episode 1 - The City Part 3"
	name 	"coopAftermathModLevels2"
	rect	275 156 328 20
	font serpentinemedium-10
	fgcolor 		1.000 1.000 1.000 0.800
	bgcolor 		0.12 0.15 0.25 0.7
	hoverbgcolor 	0.22 0.25 0.35 1.0
	
	horizontaljustify left
	verticaljustify top

	clicksound sound/misc/menu/click.wav
 
	stuffcommand "set ui_startmap coop_aftermath3\n"
	hovercommand "globalwidgetcommand coop_startserverShot shader sysimg/mapshots/coop_aftermath3.tga;globalwidgetcommand coop_startserverName title \"Daedalus\""
	hoverexitcommand "globalwidgetcommand coop_startserverShot shader sysimg/2d/default-map-screen.tga;globalwidgetcommand coop_startserverName title \"\""
}
resource
Button
{
	cvarvisibility coop_ui_vt 16 ==
	title "Episode 1 - The City Part 4"
	name 	"coopAftermathModLevels3"
	rect	275 177 328 20
	font serpentinemedium-10
	fgcolor 		1.000 1.000 1.000 0.800
	bgcolor 		0.12 0.15 0.25 0.7
	hoverbgcolor 	0.22 0.25 0.35 1.0
	
	horizontaljustify left
	verticaljustify top

	clicksound sound/misc/menu/click.wav
 
	stuffcommand "set ui_startmap coop_aftermath4\n"
	hovercommand "globalwidgetcommand coop_startserverShot shader sysimg/mapshots/coop_aftermath4.tga;globalwidgetcommand coop_startserverName title \"Daedalus\""
	hoverexitcommand "globalwidgetcommand coop_startserverShot shader sysimg/2d/default-map-screen.tga;globalwidgetcommand coop_startserverName title \"\""
}
resource
Button
{
	cvarvisibility coop_ui_vt 16 ==
	title "Episode 1 - The City Part 5"
	name 	"coopAftermathModLevels4"
	rect	275 199 328 20
	font serpentinemedium-10
	fgcolor 		1.000 1.000 1.000 0.800
	bgcolor 		0.12 0.15 0.25 0.7
	hoverbgcolor 	0.22 0.25 0.35 1.0
	
	horizontaljustify left
	verticaljustify top

	clicksound sound/misc/menu/click.wav
 
	stuffcommand "set ui_startmap coop_aftermath5\n"
	hovercommand "globalwidgetcommand coop_startserverShot shader sysimg/mapshots/coop_aftermath5.tga;globalwidgetcommand coop_startserverName title \"Daedalus\""
	hoverexitcommand "globalwidgetcommand coop_startserverShot shader sysimg/2d/default-map-screen.tga;globalwidgetcommand coop_startserverName title \"\""
}
end.

