///////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////Notify TEAM
///////////////////////////////////////////////////////////////////////////////
resource
Button
{
	title "$$c#083$$"
	name "coop_comNotifyIamback"
	rect 2 62 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I am back now : =\/\\= : Ich bin zurueck\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#084$$"
	name "coop_comNotifyBrb"
	rect 2 88 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I'll be right back : =\/\\= : Ich bin gleich wieder da\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#085$$"
	name "coop_comNotifyNeedbackup"
	rect 2 114 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I need backup!: =\/\\= : Ich brauche Unterstuetzung!\n togglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#086$$"
	name "coop_comNotifyWaitinghere"
	rect 2 140 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I am waiting here: =\/\\= : Ich warte hier\n togglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#087$$"
	name "coop_comNotifyHoldstill"
	rect 2 192 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Hold still for a Moment please! : =\/\\= : Bitte stillhalten !\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#088$$"
	name "coop_comNotifyNeedhw"
	rect 2 218 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I need a Weapon Expert! : =\/\\= : Ich brauche ein Waffenexperte!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#089$$"
	name "coop_comNotifyNeedtech"
	rect 2 244 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I need a Technican! : =\/\\= : Ich brauche ein Techniker!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}
resource
Button
{
	title "$$c#090$$"
	name "coop_comNotifyNeedmedic"
	rect 2 270 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I need a Medic! : =\/\\= : Ich brauche ein Doctor!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "3"
}

end.