////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////Functions/////TRANSPORT
////////////////////////////////////////////////////////////////////////////////
//[b607] chrissstrahl - new
resource
Button
{
	title "$$c#103$$"
	name "coop_comTransRand"
	rect 2 62 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 0"
	name "coop_comTrans0"
	rect 2 88 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 0\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 1"
	name "coop_comTrans1"
	rect 2 114 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 1\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 2"
	name "coop_comTrans2"
	rect 2 140 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 2\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 3"
	name "coop_comTrans3"
	rect 2 166 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 3\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 4"
	name "coop_comTrans4"
	rect 2 192 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 4\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 5"
	name "coop_comTrans5"
	rect 2 218 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 5\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 6"
	name "coop_comTrans6"
	rect 2 244 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 6\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}
resource
Button
{
	title "!transport 7"
	name "coop_comTrans7"
	rect 2 270 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "!transport 7\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/environment/computer/lcars_yes.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "10"
}

end.