///////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////Confirm TEAM
///////////////////////////////////////////////////////////////////////////////
resource
Button
{
	title "$$c#074$$"
	name "coop_comConfNegative"
	rect 2 62 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Negative... : =\/\\= : Negativ...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#075$$"
	name "coop_comConfModulating"
	rect 2 88 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I am Modulating... : =\/\\= : Ich Moduliere...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#076$$"
	name "coop_comConfAffirmative"
	rect 2 114 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Positive... : =\/\\= : Positiv...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#077$$"
	name "coop_comConfCovering"
	rect 2 140 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Covering you... : =\/\\= : Ich gebe Deckung...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#078$$"
	name "coop_comConfFollowing"
	rect 2 166 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Following you... : =\/\\= : Ich folge Ihnen...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#079$$"
	name "coop_comConfRetreating"
	rect 2 192 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I am retreating... : =\/\\= : Ich ziehe mich zurueck...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#080$$"
	name "coop_comConfHolding"
	rect 2 218 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Holding position... : =\/\\= : Ich halte diese Position...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#081$$"
	name "coop_comConfLeading"
	rect 2 244 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Leading the way... : =\/\\= : Ich gehe voran...\ntogglemenu coop_communicator" //fixed typo [b607]
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}
resource
Button
{
	title "$$c#082$$"
	name "coop_comConfNextobj"
	rect 2 270 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : I take the next Objective... : =\/\\= : Ich erledige naechstes Missionsziel...\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "2"
}

end.