////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////Order TEAM
////////////////////////////////////////////////////////////////////////////////
resource
Button
{
	title "$$c#065$$"
	name "coop_comFallback"
	rect 2 62 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Fallback! : =\/\\= : Rueckzug!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#066$$"
	name "coop_comCoverme"
	rect 2 88 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Cover me! : =\/\\= : Geben Sie mir Deckung!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#067$$"
	name "coop_comFollowme"
	rect 2 114 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Follow me! : =\/\\= : Folgen Sie mir!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#068$$"
	name "coop_comTakecover"
	rect 2 140 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Take cover! : =\/\\= : In Deckung!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#069$$"
	name "coop_comIncoming"
	rect 2 166 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Incoming! : =\/\\= : Eingehend!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#070$$"
	name "coop_comLeadtheway"
	rect 2 192 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Lead the way! : =\/\\= : Gehen Sie voran!\ntogglemenu coop_communicator" //fixed typo [b607]
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#071$$"
	name "coop_comMeetwithme"
	rect 2 218 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Meet with me! : =\/\\= : Stossen Sie zu mir!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#072$$"
	name "coop_comHoldposition"
	rect 2 244 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Hold this position! : =\/\\= : Halten Sie diese Position!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}
resource
Button
{
	title "$$c#073$$"
	name "coop_comTakenext"
	rect 2 270 252 24
	borderstyle "INDENT_BORDER"
	stuffcommand "say =\/\\= : Take next Objective! : =\/\\= : Naechstes Ziel uebernehmen!\ntogglemenu coop_communicator"
	font serpentinemedium-12
	verticaljustify top
	clicksound sound/player/CommunicatorBeep.wav
	fgcolor 0.99 0.80 0.20 1.00
	bgcolor 0.22 0.25 0.35 0.9
	hoverbgcolor 1 1 1 0.4
	hoverfgcolor 1 1 1 1
	cvarvisibility "coop_comL" "1"
}

end.